### ISSUE TITLE
Support for Arnold core 4.2.14.x

### ISSUE THREAD

**Issue by jo-nike** [madesjardins/Obq_Shaders#12]
Hi,

I noticed a recent update on the shaders (thanks!) but there seems to be a lack of libraries for core 4.2.14.x (goes from 13 to 15 in the bin folder). As mtoa 1.3.1 uses that core I was wondering if the omission was intended in any way?

Thanks,

**Comment by madesjardins** [comment]
It's just that I didn't bother doing 14 as it wouldn't change anything. Using 13 is okay.

**Comment by jo-nike** [comment]
Much appreciated @madesjardins !
