### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by methusalah** [madesjardins/Obq_Shaders#16]
Hi there,

I'm using your shaders to implement the marschner hair shading paper. It has been very helpful so far, thanks for the sharing ! Though I have a question or two. If you can spend a minute to that, could you please let me know your email address or else?

Thanks in advance

**Comment by madesjardins** [comment]
Hey Benoît,

You can contact me (en français si tu veux) at mdesjardins@gmail.com.

Cheers

**Comment by madesjardins** [comment]
Je me suis trompé, lol.
marcantoinedesjardins at gmail.com

**Comment by methusalah** [comment]
Je t'ai renvoyé mon mail 🤪 dis moi si tu n'as rien reçu
